services:
  api:
    image: lodgify/movies-api:3
    ports:
      - "7172:80"
      - "7443:443"
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - FailurePercentage=40
    entrypoint: sh -c "mv /app/amovies-db.json /app/movies-db.json && exec dotnet Lodgify.Api.Challenge.dll"        
  cache:
    image: "redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
